mod_id=nice
mod_name=Nice
version=26.2-6.0.0-fabric
curse_type=beta
projectId=255038
projectSlug=xnicex
modrinthId=4KbAoMmI
github_project=McJtyMods/Nice

org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_version=0.155.2+26.2
loom_version=1.17.17
forge_config_api_port_version=26.2.1
