modLoader="javafml"
loaderVersion="[43,)"
license="MIT License https://github.com/McJtyMods/XNet/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/XNet/issues"
displayURL="http://github.com/McJtyMods/XNet/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="nice"
version="${file.jarVersion}"
displayName="NICE"
#updateJSONURL="http://myurl.me/" #optional
description='''
Powerful item/fluid/energy transfer
'''
[[dependencies.nice]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nice]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.19-7.2.1,)"
    ordering="AFTER"
    side="BOTH"
