modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/Nice/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/Nice/issues"
displayURL="http://github.com/McJtyMods/Nice/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="nice"
version="${file.jarVersion}"
displayName="NICE"
#updateJSONURL="http://myurl.me/" #optional
description='''
Nice decorative blocks
'''
[[dependencies.nice]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nice]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.21-9.0.18,)"
    ordering="AFTER"
    side="BOTH"
