package mcjty.nice.particle;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import mcjty.lib.client.RenderHelper;
import mcjty.nice.Nice;
import mcjty.nice.NiceConfig;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.block.BlockRenderDispatcher;
import net.minecraft.client.renderer.texture.TextureAtlas;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.BlockModelRotation;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraftforge.client.model.data.ModelData;
import org.joml.Quaternionf;
import org.joml.Vector3f;

public class ParticleRenderer {

    public static ResourceLocation PARTICLES = new ResourceLocation(Nice.MODID, "block/effects/particles");

    public static void renderParticleSystem(IParticleProvider provider, VertexConsumer buffer, PoseStack matrixStack, TextureAtlasSprite sprite) {
        renderParticleSystem(provider, buffer, matrixStack, sprite, new Quaternionf());
    }

    private static void renderParticleSystem(IParticleProvider provider, VertexConsumer buffer, PoseStack matrixStack, TextureAtlasSprite sprite, Quaternionf rotation) {
        long time = System.currentTimeMillis();

        int brightness = 240;
        int b1 = brightness >> 16 & 65535;
        int b2 = brightness & 65535;
        IParticleSystem system = provider.getParticleSystem();
        ICalculatedParticleSystem calculated = provider.getCalculatedParticleSystem();
        if (calculated == null) {
            return;
        }
        system.update(calculated, time);

        float u0 = sprite.getU0();
        float v0 = sprite.getV0();
        float uM = sprite.getU1();
        float vM = sprite.getV1();
        float du = uM - u0;
        float dv = vM - v0;

        for (IParticle particle : calculated.getParticles()) {
            Vector3f offset = new Vector3f((float) particle.getOffset().x, (float) particle.getOffset().y, (float) particle.getOffset().z);
            offset.rotate(rotation);
            double u1 = u0 + particle.getU1() * du;
            double u2 = u0 + particle.getU2() * du;
            double v1 = v0 + particle.getV1() * dv;
            double v2 = v0 + particle.getV2() * dv;
            int r = (int) (particle.getR() * NiceConfig.particleBrightnessR);
            int g = (int) (particle.getG() * NiceConfig.particleBrightnessG);
            int b = (int) (particle.getB() * NiceConfig.particleBrightnessB);
            int a = particle.getA();
            double scale = particle.getScale();

            // Rotate the position with the cylinder, then billboard only the sprite.
            matrixStack.pushPose();
            matrixStack.translate(offset.x, offset.y, offset.z);
            RenderHelper.rotateToPlayer(matrixStack);
            RenderHelper.vt(buffer, matrixStack, (float)-scale, (float)-scale, 0, (float)u1, (float)v1, b1, b2,r, g, b, a);
            RenderHelper.vt(buffer, matrixStack, (float)-scale, (float)scale, 0, (float)u1, (float)v2, b1, b2,r, g, b, a);
            RenderHelper.vt(buffer, matrixStack, (float)scale, (float)scale, 0, (float)u2, (float)v2, b1, b2,r, g, b, a);
            RenderHelper.vt(buffer, matrixStack, (float)scale, (float)-scale, 0, (float)u2, (float)v1, b1, b2,r, g, b, a);
            matrixStack.popPose();
        }
    }

    public static void renderSystem(PoseStack stack, MultiBufferSource buf, IParticleProvider provider) {
        renderSystem(stack, buf, provider, Direction.UP);
    }

    public static void renderSystem(PoseStack stack, MultiBufferSource buf, IParticleProvider provider, Direction facing) {
        // Match the rotations generated by directionalBlock for an upright model.
        int x = facing == Direction.DOWN ? 180 : facing.getAxis().isHorizontal() ? 90 : 0;
        int y = facing.getAxis().isVertical() ? 0 : ((int) facing.toYRot() + 180) % 360;
        Quaternionf rotation = BlockModelRotation.by(x, y).getRotation().getLeftRotation();
        VertexConsumer buffer = buf.getBuffer(ParticleRenderTypes.TRANSLUCENT_PARTICLES);
        stack.pushPose();
        stack.translate(0.5F, 0.5F, 0.5F);
        TextureAtlasSprite sprite = Minecraft.getInstance().getTextureAtlas(TextureAtlas.LOCATION_BLOCKS).apply(PARTICLES);
        renderParticleSystem(provider, buffer, stack, sprite, rotation);
        stack.popPose();
    }

    public static void renderBlock(PoseStack stack, MultiBufferSource buf, BlockState state, int combinedLight, int combinedOverlay, RenderType renderType) {
        BlockRenderDispatcher renderer = Minecraft.getInstance().getBlockRenderer();
        BakedModel model = renderer.getBlockModel(state);
        int color = Minecraft.getInstance().getBlockColors().getColor(state, null, null, 0);
        float r = (float) (color >> 16 & 255) / 255.0F;
        float g = (float) (color >> 8 & 255) / 255.0F;
        float b = (float) (color & 255) / 255.0F;
        VertexConsumer buffer = buf.getBuffer(ParticleRenderTypes.TRANSLUCENT_PARTICLES);
        RenderHelper.renderModel(renderer, stack, buffer, state, model, r, g, b, combinedLight, combinedOverlay, ModelData.EMPTY, renderType);
    }

}
